services:
  db_postgres:
    container_name: efcore_migrations
    image: postgres:15.2-alpine
    ports:
      - "6172:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345